package_rename_config:
  android:
    app_name: AeroXpress
    package_name: com.saino.aero_xpress
    override_old_package: com.example.aero_xpress
    lang:

  ios:
    app_name: AeroXpress
    bundle_name: AeroXpress
    package_name: com.example.aero_xpress