name: aero_xpress
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.24.0
  package_rename: ^1.10.0
  responsive_builder: ^0.7.1
  toastification: ^3.0.2
  url_launcher: ^6.3.1
  provider: ^6.1.4
  go_router: ^15.0.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    - assets/svg/
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
        - asset: assets/fonts/Roboto_Medium.ttf
        - asset: assets/fonts/Roboto_Bold.ttf
        - asset: assets/fonts/Roboto_Light.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins_Regular.ttf
        - asset: assets/fonts/Poppins/Poppins_Medium.ttf
        - asset: assets/fonts/Poppins/Poppins_Bold.ttf
        - asset: assets/fonts/Poppins/Poppins_Light.ttf
